stages:
  - build
  - test

build-job:
  image: rust:latest
  stage: build
  script:
    - cargo build build
  artifacts:
    paths:
      - "target/"

test-job:
  image: rust:latest
  stage: test
  script:
    - cargo fmt
    - cargo check
    - cargo test
  dependencies:
    - build-job

