stages:
  - build
  - test

build-job:
  image: rust:latest
  stage: build
  variables:
    APP_ENV: production
  script:
    # - cargo build --release
    - echo "Building project...."
    - sleep 5
    - echo "Built successfully."
  artifacts:
    paths:
      - target/

test-job:
  image: rust:latest
  stage: test
  services:
    - name: postgres
      alias: test_db
  variables:
    POSTGRES_USER: postres
    POSTGRES_PASSWORD: password
    POSTGRES_DB: newsletter
    PORTGRES_PORT: 5432
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_HOST: test_db
    PGPASSWORD: $POSTGRES_PASSWORD
    APP_ENV: development

  script:
    - apt-get update && apt-get install -y postgresql-client nmap
    - env | grep ^POSTGRES
    - nmap $POSTGRES_HOST
    - sleep 10
    - if ! psql -U $POSTGRES_USER -d $POSTGRES_DB -h $POSTGRES_HOST -p $POSTGRES_PORT -c '\q'; then echo "Postgres Still not responding"; fi
    # - cargo check
    # - cargo test
  dependencies:
    - build-job

